name: update

permissions:
  contents: write

on:
  push:
    branches:
      - dev
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
  workflow_dispatch:
# schedule:
  # - cron: "0 0 * * *"

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          git config --global init.defaultBranch main
          git config --global user.email "mpv-easy@mpv.com"
          git config --global user.name "mpv-easy-build"
          git config --global --type bool push.autoSetupRemote true

          git clone https://github.com/mpv-easy/mpv-easy.git ../mpv-easy
          cd ../mpv-easy
          # TODO: change to main
          git checkout mpv-build
          pnpm i
          pnpm run build

      - name: commit
        run: |
          cp -rf ../mpv-easy/mpv-build/dist/* ./

          ls -l

          git init
          git remote add origin https://github.com/mpv-easy/mpv-build.git
          git add .
          git commit -am "update by ci"

      - name: ls
        run: |
          ls -l
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
