name: update

permissions:
  contents: write

on:
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          git clone https://github.com/mpv-easy/mpv-easy.git ../mpv-easy
          cd ../mpv-easy
          pnpm i
          pnpm run build



      - name: commit
        run: |
          cp -rf ../mpv-easy/mpv-build/dist/* ./

          ls -l

          git init
          git remote add origin https://github.com/mpv-easy/mpv-build.git
          git add .
          git commit -am "update by ci"

      - name: ls
        run: |
          ls -l
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          # force_with_lease: true
          force: true
